In [1]:
import numpy as np

In [3]:
np.set_printoptions(suppress=True, precision=2)

In [5]:
raw_data_np = np.genfromtxt("loan-data.csv", delimiter = ';', skip_header = 1, autostrip = True)
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,
                nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,
                nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,
                nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,
                nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,
                nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,
                nan,      301.9 ]])

In [7]:
np.isnan(raw_data_np).sum()

91500

In [9]:
temporary_fill = np.nanmax(raw_data_np) + 1
temporary_mean = np.nanmean(raw_data_np, axis = 0)

C:\Users\acer\AppData\Local\Temp\ipykernel_10160\3983241459.py:2: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data_np, axis = 0)


In [13]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,
               nan,        0.01,      440.92,         nan,         nan,
               nan,         nan,         nan,     3143.85])

In [15]:
temporary_stats = np.array([np.nanmin(raw_data_np, axis = 0),
                           temporary_mean,
                           np.nanmax(raw_data_np, axis = 0)])


C:\Users\acer\AppData\Local\Temp\ipykernel_10160\1851770469.py:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data_np, axis = 0),
C:\Users\acer\AppData\Local\Temp\ipykernel_10160\1851770469.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np, axis = 0)])


In [17]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,
                nan,        0.  ,       31.42,         nan,         nan,
                nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,
                nan,        0.01,      440.92,         nan,         nan,
                nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,
                nan,        6.  ,     1372.97,         nan,         nan,
                nan,         nan,         nan,    41913.62]])

In [19]:
column_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [21]:
column_numeric = np.argwhere(np.isnan(temporary_mean) == False).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [23]:
loan_data_strings = np.genfromtxt("loan-data.csv", 
                                  delimiter = ';', 
                                  skip_header = 1, 
                                  autostrip = True,
                                  usecols = column_strings,
                                  dtype = str)
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
        'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
        'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726',
        'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
        'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
        'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249',
        'IL']], dtype='<U69')

In [27]:
def comma_to_dot(x):
    return float(x.decode('utf-8').replace(',', '.'))

In [29]:
loan_data_numeric = np.genfromtxt("loan-data.csv", 
                                  delimiter=';', 
                                  skip_header=1, 
                                  autostrip=True,
                                  usecols=column_numeric,
                                  filling_values=temporary_fill,
                                  converters={col: comma_to_dot for col in column_numeric})
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,
            9452.96],
       [57693261.  ,    30000.  ,    30000.  ,        7.89,      938.57,
            4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       11.53,      494.86,
            1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,        7.89, 68616520.  ,
            2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,
            3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,        7.26,      309.97,
             301.9 ]])

In [31]:
header_full = np.genfromtxt("loan-data.csv", 
                                  delimiter = ';', 
                                  autostrip = True,
                                  skip_footer = raw_data_np.shape[0],
                                  dtype = str)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term',
       'int_rate', 'installment', 'grade', 'sub_grade',
       'verification_status', 'url', 'addr_state', 'total_pymnt'],
      dtype='<U19')

In [33]:
header_strings, header_numeric = header_full[column_strings], header_full[column_numeric]

In [35]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade',
       'verification_status', 'url', 'addr_state'], dtype='<U19')

In [37]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment',
       'total_pymnt'], dtype='<U19')

In [39]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return checkpoint_variable

In [41]:
checkpoint_test = checkpoint("checkpoint-test", header_strings, loan_data_strings)

In [43]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
        'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
        'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726',
        'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
        'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
        'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249',
        'IL']], dtype='<U69')

In [45]:
np.array_equal(checkpoint_test['data'], loan_data_strings)

True

In [47]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade',
       'verification_status', 'url', 'addr_state'], dtype='<U19')

In [49]:
header_strings[0] = 'issue_date'

In [51]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15',
       'Jun-15', 'Mar-15', 'May-15', 'Nov-15', 'Oct-15', 'Sep-15'],
      dtype='<U69')

In [53]:
loan_data_strings[:,0] = np.chararray.strip(loan_data_strings[:,0], '-15')

In [55]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May',
       'Nov', 'Oct', 'Sep'], dtype='<U69')

In [57]:
months = np.array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May',
       'Nov', 'Oct', 'Sep'])

In [59]:
for i in range(13):
    loan_data_strings[:,0] = np.where(loan_data_strings[:,0] == months[i],
                                     i,
                                     loan_data_strings[:,0])

In [61]:
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'],
      dtype='<U69')

In [63]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade',
       'verification_status', 'url', 'addr_state'], dtype='<U19')

In [65]:
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid',
       'In Grace Period', 'Issued', 'Late (16-30 days)',
       'Late (31-120 days)'], dtype='<U69')

In [67]:
status_bad = np.array(['', 'Charged Off', 'Default','Late (31-120 days)'])

In [69]:
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1], 
                                          status_bad), 0, 1)

In [71]:
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

In [73]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade',
       'verification_status', 'url', 'addr_state'], dtype='<U19')

In [75]:
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [77]:
loan_data_strings[:,2] = np.chararray.strip(loan_data_strings[:,2], ' months')
loan_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [79]:
header_strings[2] = 'term_months'

In [81]:
loan_data_strings[:,2] = np.where(loan_data_strings[:,2] == '', '60', loan_data_strings[:,2])
loan_data_strings[:,2] 

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [83]:
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

In [85]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade',
       'verification_status', 'url', 'addr_state'], dtype='<U19')

In [87]:
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [89]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5',
       'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1',
       'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2',
       'G3', 'G4', 'G5'], dtype='<U69')

In [91]:
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '')&(loan_data_strings[:,3] == i),
                                      i + '5',
                                      loan_data_strings[:,4])

In [93]:
np.unique(loan_data_strings[:,4], return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5',
        'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1',
        'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2',
        'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567,
        586, 564, 577, 391, 267, 250, 255, 288, 235, 162, 171, 139, 160,
         94,  52,  34,  43,  24,  19,  10,   3,   7,   5], dtype=int64))

In [95]:
loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == ''), 'H1', loan_data_strings[:,4])

In [97]:
np.unique(loan_data_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1',
       'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2',
       'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2', 'G3',
       'G4', 'G5', 'H1'], dtype='<U69')

In [99]:
loan_data_strings = np.delete(loan_data_strings, 3, axis = 1)

In [101]:
header_strings = np.delete(header_strings, 3)

In [103]:
header_strings[3] 

'sub_grade'

In [105]:
keys = list(np.unique(loan_data_strings[:,3]))
values = list(range(1, len(np.unique(loan_data_strings[:,3])) + 1))
dict_sub_grade = dict(zip(keys, values))
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [107]:
for i in np.unique(loan_data_strings[:,3]):
    loan_data_strings[:,3] = np.where(loan_data_strings[:,3] == i,
                                      dict_sub_grade[i],
                                      loan_data_strings[:,3])

In [109]:
np.unique(loan_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19',
       '2', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29',
       '3', '30', '31', '32', '33', '34', '35', '36', '4', '5', '6', '7',
       '8', '9'], dtype='<U69')

In [111]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade',
       'verification_status', 'url', 'addr_state'], dtype='<U19')

In [113]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [115]:
loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') | (loan_data_strings[:,4] == 'Not Verified'), 0, 1)
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

In [117]:
loan_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726',
       ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'],
      dtype='<U69')

In [119]:
loan_data_strings[:,5] = np.chararray.strip(loan_data_strings[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')
loan_data_strings[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151',
       '66055249'], dtype='<U69')

In [121]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term',
       'int_rate', 'installment', 'grade', 'sub_grade',
       'verification_status', 'url', 'addr_state', 'total_pymnt'],
      dtype='<U19')

In [123]:
loan_data_numeric[:,0].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [125]:
loan_data_strings[:,5].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [127]:
np.array_equal(loan_data_numeric[:,0].astype(dtype = np.int32), loan_data_strings[:,5].astype(dtype = np.int32))

True

In [129]:
loan_data_strings = np.delete(loan_data_strings, 5, axis = 1)
header_strings = np.delete(header_strings, 5)

In [131]:
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [133]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade',
       'verification_status', 'addr_state'], dtype='<U19')

In [135]:
header_strings[5] = 'state_adress'

In [137]:
state_names, state_counts = np.unique(loan_data_strings[:,5], return_counts = True)
state_counts_sorted = np.argsort(-state_counts)
state_names[state_counts_sorted], state_counts[state_counts_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI',
        'NC', 'VA', 'MD', 'AZ', 'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI',
        'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY', 'KS', 'OK', 'UT',
        'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY',
        'AK', 'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,
         261,  242,  222,  220,  216,  210,  201,  160,  156,  152,  148,
         143,  143,  130,  119,  116,  108,  107,   84,   84,   83,   74,
          74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,
          26,   25,   24,   17,   16,   10], dtype=int64))

In [139]:
loan_data_strings[:,5] = np.where(loan_data_strings[:,5] == '', 0, loan_data_strings[:,5]) 

In [141]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [143]:
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_west ), 1, loan_data_strings[:,5]) 
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_south), 2, loan_data_strings[:,5]) 
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_midwest ), 3, loan_data_strings[:,5]) 
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_east ), 4, loan_data_strings[:,5]) 

In [145]:
np.unique(loan_data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [147]:
loan_data_strings

array([['9', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['12', '1', '36', '10', '1', '4'],
       ...,
       ['7', '1', '36', '5', '1', '1'],
       ['1', '1', '36', '17', '1', '3'],
       ['3', '1', '36', '4', '0', '3']], dtype='<U69')

In [149]:
loan_data_strings = loan_data_strings.astype(int)

In [151]:
loan_data_strings

array([[ 9,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [12,  1, 36, 10,  1,  4],
       ...,
       [ 7,  1, 36,  5,  1,  1],
       [ 1,  1, 36, 17,  1,  3],
       [ 3,  1, 36,  4,  0,  3]])

In [153]:
checkpoint_strings = checkpoint("checkpoint-string", header_strings, loan_data_strings)

In [155]:
checkpoint_strings["header"]


array(['issue_date', 'loan_status', 'term_months', 'sub_grade',
       'verification_status', 'state_adress'], dtype='<U19')

In [157]:
checkpoint_strings["data"]

array([[ 9,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [12,  1, 36, 10,  1,  4],
       ...,
       [ 7,  1, 36,  5,  1,  1],
       [ 1,  1, 36, 17,  1,  3],
       [ 3,  1, 36,  4,  0,  3]])

In [159]:
np.array_equal(checkpoint_strings["data"], loan_data_strings)

True

In [161]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment',
       'total_pymnt'], dtype='<U19')

In [163]:
temporary_fill

68616520.0

In [165]:
np.isin(loan_data_numeric[:,0], temporary_fill)

array([False, False, False, ..., False, False, False])

In [167]:
np.isin(loan_data_numeric[:,0], temporary_fill).sum()

0

In [169]:
temporary_stats[:, column_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        0.  ,       31.42,
               0.  ],
       [54015809.19,    15273.46,    15311.04,        0.01,      440.92,
            3143.85],
       [68616519.  ,    35000.  ,    35000.  ,        6.  ,     1372.97,
           41913.62]])

In [171]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [173]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temporary_fill, 
                                  temporary_stats[0, column_numeric[2]],
                                  loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [175]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment',
       'total_pymnt'], dtype='<U19')

In [177]:
for i in [1, 3, 4, 5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == temporary_fill, 
                                  temporary_stats[0, column_numeric[i]],
                                  loan_data_numeric[:,i])

In [179]:
EUR_USD = np.genfromtxt("EUR-USD.csv", delimiter = ',', autostrip = True, skip_header = 1, usecols = 3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06,
       1.09])

In [181]:
loan_data_strings[:,0]

array([ 9,  0, 12, ...,  7,  1,  3])

In [183]:
exchange_rate = loan_data_strings[:,0]

for i in range(1, 13):
    exchange_rate = np.where(exchange_rate == i,
                            EUR_USD[i-1],
                            exchange_rate)
    
exchange_rate = np.where(exchange_rate == 0,
                            np.mean(EUR_USD),
                            exchange_rate)

exchange_rate

array([1.13, 1.11, 1.09, ..., 1.09, 1.13, 1.08])

In [185]:
exchange_rate = np.reshape(exchange_rate, (10000, 1))

In [187]:
loan_data_numeric = np.hstack((loan_data_numeric, exchange_rate))
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,
            9452.96,        1.13],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,
            4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,
            1969.83,        1.09],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,       31.42,
            2185.64,        1.09],
       [46154151.  ,     1000.  ,    10000.  , ...,      354.3 ,
            3199.4 ,        1.13],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,
             301.9 ,        1.08]])

In [189]:
header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate'])))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment',
       'total_pymnt', 'exchange_rate'], dtype='<U19')

In [191]:
colums_dollar = np.array([1,2,4,5])

In [193]:
np.unique(loan_data_numeric[:,6])

array([1.06, 1.08, 1.09, 1.09, 1.1 , 1.1 , 1.11, 1.11, 1.12, 1.12, 1.13,
       1.13, 1.13])

In [195]:
for i in colums_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric, np.reshape(loan_data_numeric[:,i]/loan_data_numeric[:,6],(10000, 1))))
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31094.7 ,
            1052.65,     8398.2 ],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,
             848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13718.7 ,
             452.59,     1801.57],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     9141.4 ,
              28.72,     1997.98],
       [46154151.  ,     1000.  ,    10000.  , ...,     8859.  ,
             313.87,     2834.35],
       [66055249.  ,    10000.  ,    10000.  , ...,     9233.4 ,
             286.21,      278.76]])

In [199]:
header_aditional = np.array([column_name + '_EUR' for column_name in header_numeric[colums_dollar]])
header_aditional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR',
       'total_pymnt_EUR'], dtype='<U15')

In [201]:
header_numeric = np.concatenate((header_numeric, header_aditional))
header_numeric 

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment',
       'total_pymnt', 'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR',
       'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [203]:
column_index_order = [0, 1, 7, 2, 8, 3, 4, 9, 5, 10, 6]

In [205]:
header_numeric[column_index_order]

array(['id', 'loan_amnt', 'loan_amnt_EUR', 'funded_amnt',
       'funded_amnt_EUR', 'int_rate', 'installment', 'installment_EUR',
       'total_pymnt', 'total_pymnt_EUR', 'exchange_rate'], dtype='<U19')

In [207]:
header_numeric = header_numeric[column_index_order]

In [209]:
loan_data_numeric = loan_data_numeric[:,column_index_order]

In [213]:
loan_data_numeric[:,5] = loan_data_numeric[:,5]/100

In [215]:
loan_data_numeric[:,5] 

array([0.13, 0.08, 0.12, ..., 0.08, 0.17, 0.07])

In [217]:
checkpoint_numeric = checkpoint("checkpoint-numeric", header_numeric, loan_data_numeric)

In [221]:
checkpoint_numeric["header"], checkpoint_numeric["data"]

(array(['id', 'loan_amnt', 'loan_amnt_EUR', 'funded_amnt',
        'funded_amnt_EUR', 'int_rate', 'installment', 'installment_EUR',
        'total_pymnt', 'total_pymnt_EUR', 'exchange_rate'], dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31094.7 , ...,     9452.96,
             8398.2 ,        1.13],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,
             4232.39,        1.11],
        [59432726.  ,    15000.  ,    13718.7 , ...,     1969.83,
             1801.57,        1.09],
        ...,
        [50415990.  ,    10000.  ,     9141.4 , ...,     2185.64,
             1997.98,        1.09],
        [46154151.  ,     1000.  ,      885.9 , ...,     3199.4 ,
             2834.35,        1.13],
        [66055249.  ,    10000.  ,     9233.4 , ...,      301.9 ,
              278.76,        1.08]]))

In [223]:
checkpoint_strings["data"].shape

(10000, 6)

In [225]:
checkpoint_numeric["data"].shape

(10000, 11)

In [231]:
loan_data = np.hstack((checkpoint_numeric["data"], checkpoint_strings["data"]))
loan_data

array([[48010226.  ,    35000.  ,    31094.7 , ...,       13.  ,
               1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,
               1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13718.7 , ...,       10.  ,
               1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     9141.4 , ...,        5.  ,
               1.  ,        1.  ],
       [46154151.  ,     1000.  ,      885.9 , ...,       17.  ,
               1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9233.4 , ...,        4.  ,
               0.  ,        3.  ]])

In [233]:
np.isnan(loan_data).sum()

0

In [235]:
header_full = np.concatenate((checkpoint_numeric["header"], checkpoint_strings["header"]))

In [239]:
loan_data = loan_data[np.argsort(loan_data[:,0])]
loan_data

array([[  373332.  ,     9950.  ,     9401.85, ...,       21.  ,
               0.  ,        1.  ],
       [  575239.  ,    12000.  ,    11338.92, ...,       25.  ,
               1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8997.4 , ...,       13.  ,
               1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5170.7 , ...,        8.  ,
               1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3693.36, ...,       10.  ,
               1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19944.14, ...,        3.  ,
               0.  ,        2.  ]])

In [241]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

In [243]:
loan_data = np.vstack((header_full, loan_data))

In [253]:
np.savetxt('loan-data-preprocessed.csv',
           loan_data,
           fmt="%s",
           delimiter=',')
